### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by isaiahclemons7** [ignition-devs/ignition-api-8.1#304]
Hello what would it take and is it on the timeline to make this project compatible with Python3.x instead of just python 2.7? Thank you, big fan of the project and excited to see where it goes!

**Comment by cesarcoatl** [comment]
> Hello @isaiahclemons7.
> 
> The decision to keep `ignition-api` locked to Python 2.7 stems from several key considerations.
> 
> First and foremost, I wanted to ensure consistency and minimize potential confusion for users already working with this package and Ignition itself. As you may know, Ignition by Inductive Automation relies on Jython—a Java implementation of Python. Unfortunately, the most recent stable version of Jython (2.7.3) is based on Python 2.7, meaning that core Ignition scripting and many API interactions require Python 2.7 compatibility. Introducing Python 3 support into this package could potentially cause inconsistencies for users who expect smooth integration with Ignition’s scripting environment.
> 
> If at some point Inductive Automation transitions to Python 3, then this package will follow suit to maintain alignment with the platform and ensure smooth integration with the updated ecosystem.
> 
> Thanks, César

https://github.com/orgs/ignition-devs/discussions/2#discussioncomment-10949540
